### ISSUE TITLE
is it still maintained

### ISSUE THREAD

**Issue by clarkk** [mseebach/PBS-parser#1]
I would just like to check if the library is still maintained and working (in production)? :)

**Comment by mseebach** [comment]
No on both accounts (although there's no reason to believe it doesn't work, for the limited use case it was built). Good luck.

**Comment by clarkk** [comment]
Ok.. What were you using it for?

I believe it can send a 601 (send payments) and do a 602 (retrieve a payment status) ?

Can it do more then that?

**Comment by mseebach** [comment]
I was using it to charge recurring membership fees for an organisation, and receive the notifications of payments. I don't recall the mechanics, but it sounds like those are the two message types, yes.

**Comment by nicknick-io** [comment]
@clarkk We might have some PHP Code samples available, as we've recently done some integration work. What kind of charges are you looking to do? Membership, contract-based, one-off charges? Just curious. 🙂

**Comment by clarkk** [comment]
@nicknick-io sounds good..

I'm not 100% sure.. But need to do 601, 602 and 603

**Comment by nicknick-io** [comment]
@clarkk Arh, just curious about the business logic. Was it like a "one-off" charge for some service, or is it like rent/insurance where you need to charge from next month the 1. and forward until termination, or is it the (possibly) really complicated solution with subscriptions where you need to charge now (through paper / e-boks) and then from a fixed date moving forward?

You are correct in you need 0601, 0602, 0603 and possibly 0605 too if you are to manually register mandates. There are LOTS of possible files.

**Comment by clarkk** [comment]
Ohh.. It's a recurring/subscription service where the creditor can invoice the customer at any point in time

When a creditor invoice I need to put a deferred payment to next due date which is 6th last bank day in each month.. So yes it might get a little complicated :)

So you can manually register via bank details (605) ? But I don't think I need that one

But I develop in PHP so in any case any code would be welcome to at least for inspiration use :)

**Comment by clarkk** [comment]
@nicknick-io But I have made a PHP script which calculates the 6th last bank day in each month.. if you are interested.. It even takes holidays in account

**Comment by oliverbj** [comment]
@clarkk Did you ever get a chance to implement PHP with Betalingsservice? I am looking to do the same, and would like to get some inspiration on where to start :)

**Comment by oliverbj** [comment]
Or perhaps @nicknick-io you have something? (Sorry for tagging, but Betalingsservice flat files are like a black hole to work with...). FYI I am using Laravel/PHP.

**Comment by nicknick-io** [comment]
@oliverbj My team actually managed to get it working, it is currently being used live in a project that i cannot disclose - Although I probably have the code somewhere, i'll not be able to share it since i could get sued.

**Comment by oliverbj** [comment]
> My team actually managed to get it working, it is currently being used live in a project that i cannot disclose - Although I probably have the code somewhere, i'll not be able to share it since i could get sued.

Ah, no worries! Thanks for getting back so fast. Enjoy your weekend!
